/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestLayout1.java
 *
 * Created on Jul 13, 2011, 2:07:41 PM
 */

package vn.smartbiz.pos.Product;

/**
 *
 * @author Administrator
 */
public class JProduct extends javax.swing.JPanel {

    /** Creates new form TestLayout1 */
    public JProduct() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel = new javax.swing.JPanel();
        jPBLMain = new javax.swing.JPanel();
        jPFLSub = new javax.swing.JPanel();
        jPBLTop = new javax.swing.JPanel();
        jPGBLProduct = new javax.swing.JPanel();
        jLProductName = new javax.swing.JLabel();
        jLUnit = new javax.swing.JLabel();
        jTProductID = new javax.swing.JTextField();
        jTProductName = new javax.swing.JTextField();
        jCbUnit = new javax.swing.JComboBox();
        jLTax = new javax.swing.JLabel();
        jCbTax = new javax.swing.JComboBox();
        jLProductID = new javax.swing.JLabel();
        jLActive = new javax.swing.JLabel();
        jLDescription = new javax.swing.JLabel();
        jTDescription = new javax.swing.JTextField();
        jCbActive = new javax.swing.JCheckBox();
        jLProductImage = new javax.swing.JLabel();
        jPBLMiddle = new javax.swing.JPanel();
        jPGBLCatagory = new javax.swing.JPanel();
        jLBarcode = new javax.swing.JLabel();
        jTBarcode = new javax.swing.JTextField();
        jLBrandName = new javax.swing.JLabel();
        jCbBrandName = new javax.swing.JComboBox();
        jLSex = new javax.swing.JLabel();
        jCbSex = new javax.swing.JComboBox();
        jLCatagory = new javax.swing.JLabel();
        jCbCatagory = new javax.swing.JComboBox();
        jLSeason = new javax.swing.JLabel();
        jCbSeason = new javax.swing.JComboBox();
        jLYear = new javax.swing.JLabel();
        jTYear = new javax.swing.JTextField();
        jPBLBottom = new javax.swing.JPanel();
        jPGBLAttribute = new javax.swing.JPanel();
        jLProductType = new javax.swing.JLabel();
        jCbProductType = new javax.swing.JComboBox();
        jLProductSize = new javax.swing.JLabel();
        jCbProductSize = new javax.swing.JComboBox();
        jLProductColor = new javax.swing.JLabel();
        jCbProductColor = new javax.swing.JComboBox();
        jLCollection = new javax.swing.JLabel();
        jCbCollection = new javax.swing.JComboBox();
        jPBLEnd = new javax.swing.JPanel();
        jPGBLReference = new javax.swing.JPanel();
        jLMaterial = new javax.swing.JLabel();
        jCbMaterial = new javax.swing.JComboBox();
        jLType = new javax.swing.JLabel();
        jCbType = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Sản Phẩm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.CardLayout());

        jPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel.setName("jPanel"); // NOI18N
        jPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel.setLayout(new java.awt.CardLayout());

        jPBLMain.setMaximumSize(new java.awt.Dimension(800, 600));
        jPBLMain.setMinimumSize(new java.awt.Dimension(800, 600));
        jPBLMain.setName("jPBLMain"); // NOI18N
        jPBLMain.setPreferredSize(new java.awt.Dimension(800, 600));
        jPBLMain.setLayout(new java.awt.BorderLayout());

        jPFLSub.setBackground(new java.awt.Color(201, 222, 249));
        jPFLSub.setMaximumSize(new java.awt.Dimension(800, 700));
        jPFLSub.setMinimumSize(new java.awt.Dimension(800, 700));
        jPFLSub.setName("jPFLSub"); // NOI18N
        jPFLSub.setPreferredSize(new java.awt.Dimension(800, 700));

        jPBLTop.setBackground(new java.awt.Color(204, 204, 204));
        jPBLTop.setMaximumSize(new java.awt.Dimension(800, 230));
        jPBLTop.setMinimumSize(new java.awt.Dimension(800, 230));
        jPBLTop.setName("jPBLTop"); // NOI18N
        jPBLTop.setPreferredSize(new java.awt.Dimension(800, 230));
        jPBLTop.setLayout(new java.awt.BorderLayout());

        jPGBLProduct.setBackground(new java.awt.Color(182, 214, 255));
        jPGBLProduct.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPGBLProduct.setMaximumSize(new java.awt.Dimension(800, 265));
        jPGBLProduct.setMinimumSize(new java.awt.Dimension(800, 265));
        jPGBLProduct.setName("jPGBLProduct"); // NOI18N
        jPGBLProduct.setLayout(new java.awt.GridBagLayout());

        jLProductName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLProductName.setText("Tên");
        jLProductName.setMaximumSize(new java.awt.Dimension(80, 15));
        jLProductName.setMinimumSize(new java.awt.Dimension(80, 15));
        jLProductName.setName("jLProductName"); // NOI18N
        jLProductName.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 16, 0, 0);
        jPGBLProduct.add(jLProductName, gridBagConstraints);

        jLUnit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLUnit.setText("ĐVT");
        jLUnit.setMaximumSize(new java.awt.Dimension(80, 15));
        jLUnit.setMinimumSize(new java.awt.Dimension(80, 15));
        jLUnit.setName("jLUnit"); // NOI18N
        jLUnit.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        jPGBLProduct.add(jLUnit, gridBagConstraints);

        jTProductID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTProductID.setText("ALAT2104");
        jTProductID.setMaximumSize(new java.awt.Dimension(210, 21));
        jTProductID.setMinimumSize(new java.awt.Dimension(210, 21));
        jTProductID.setName("jTProductID"); // NOI18N
        jTProductID.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 0, 0);
        jPGBLProduct.add(jTProductID, gridBagConstraints);

        jTProductName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTProductName.setText("ALAT2104");
        jTProductName.setMaximumSize(new java.awt.Dimension(210, 21));
        jTProductName.setMinimumSize(new java.awt.Dimension(210, 21));
        jTProductName.setName("jTProductName"); // NOI18N
        jTProductName.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 4, 0, 0);
        jPGBLProduct.add(jTProductName, gridBagConstraints);

        jCbUnit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCbUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cái" }));
        jCbUnit.setMaximumSize(new java.awt.Dimension(52, 21));
        jCbUnit.setMinimumSize(new java.awt.Dimension(52, 21));
        jCbUnit.setName("jCbUnit"); // NOI18N
        jCbUnit.setPreferredSize(new java.awt.Dimension(52, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        jPGBLProduct.add(jCbUnit, gridBagConstraints);

        jLTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTax.setText("Thuế");
        jLTax.setMaximumSize(new java.awt.Dimension(80, 15));
        jLTax.setMinimumSize(new java.awt.Dimension(80, 15));
        jLTax.setName("jLTax"); // NOI18N
        jLTax.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 22, 0, 0);
        jPGBLProduct.add(jLTax, gridBagConstraints);

        jCbTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCbTax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0%", "5%", "10%" }));
        jCbTax.setMaximumSize(new java.awt.Dimension(52, 21));
        jCbTax.setMinimumSize(new java.awt.Dimension(52, 21));
        jCbTax.setName("jCbTax"); // NOI18N
        jCbTax.setPreferredSize(new java.awt.Dimension(52, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        jPGBLProduct.add(jCbTax, gridBagConstraints);

        jLProductID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLProductID.setForeground(new java.awt.Color(255, 0, 0));
        jLProductID.setText("Mã SP");
        jLProductID.setMaximumSize(new java.awt.Dimension(80, 15));
        jLProductID.setMinimumSize(new java.awt.Dimension(80, 15));
        jLProductID.setName("jLProductID"); // NOI18N
        jLProductID.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 16, 0, 0);
        jPGBLProduct.add(jLProductID, gridBagConstraints);

        jLActive.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLActive.setText("Hiệu Lực");
        jLActive.setMaximumSize(new java.awt.Dimension(80, 15));
        jLActive.setMinimumSize(new java.awt.Dimension(80, 15));
        jLActive.setName("jLActive"); // NOI18N
        jLActive.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        jPGBLProduct.add(jLActive, gridBagConstraints);

        jLDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDescription.setText("Diễn Giải");
        jLDescription.setMaximumSize(new java.awt.Dimension(80, 15));
        jLDescription.setMinimumSize(new java.awt.Dimension(80, 15));
        jLDescription.setName("jLDescription"); // NOI18N
        jLDescription.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        jPGBLProduct.add(jLDescription, gridBagConstraints);

        jTDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTDescription.setText("Áo Thun Nữ");
        jTDescription.setMaximumSize(new java.awt.Dimension(630, 21));
        jTDescription.setMinimumSize(new java.awt.Dimension(630, 21));
        jTDescription.setName("jTDescription"); // NOI18N
        jTDescription.setPreferredSize(new java.awt.Dimension(630, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 33, 70);
        jPGBLProduct.add(jTDescription, gridBagConstraints);

        jCbActive.setBackground(new java.awt.Color(182, 214, 255));
        jCbActive.setSelected(true);
        jCbActive.setName("jCbActive"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPGBLProduct.add(jCbActive, gridBagConstraints);

        jLProductImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProductImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/ALAT2104.png"))); // NOI18N
        jLProductImage.setToolTipText("Áo Thun Nữ");
        jLProductImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLProductImage.setMaximumSize(new java.awt.Dimension(210, 176));
        jLProductImage.setMinimumSize(new java.awt.Dimension(210, 176));
        jLProductImage.setName("jLProductImage"); // NOI18N
        jLProductImage.setPreferredSize(new java.awt.Dimension(210, 176));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipady = -39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 210, 0, 70);
        jPGBLProduct.add(jLProductImage, gridBagConstraints);

        jPBLTop.add(jPGBLProduct, java.awt.BorderLayout.CENTER);

        jPFLSub.add(jPBLTop);

        jPBLMiddle.setBackground(new java.awt.Color(204, 204, 204));
        jPBLMiddle.setForeground(new java.awt.Color(204, 204, 204));
        jPBLMiddle.setMaximumSize(new java.awt.Dimension(800, 153));
        jPBLMiddle.setMinimumSize(new java.awt.Dimension(800, 153));
        jPBLMiddle.setName("jPBLMiddle"); // NOI18N
        jPBLMiddle.setPreferredSize(new java.awt.Dimension(800, 153));
        jPBLMiddle.setLayout(new java.awt.BorderLayout());

        jPGBLCatagory.setBackground(new java.awt.Color(182, 214, 255));
        jPGBLCatagory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phân Loại Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPGBLCatagory.setMaximumSize(new java.awt.Dimension(800, 153));
        jPGBLCatagory.setName("jPGBLCatagory"); // NOI18N
        jPGBLCatagory.setRequestFocusEnabled(false);
        jPGBLCatagory.setLayout(new java.awt.GridBagLayout());

        jLBarcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLBarcode.setForeground(new java.awt.Color(255, 0, 0));
        jLBarcode.setText("Barcode");
        jLBarcode.setMaximumSize(new java.awt.Dimension(80, 15));
        jLBarcode.setMinimumSize(new java.awt.Dimension(80, 15));
        jLBarcode.setName("jLBarcode"); // NOI18N
        jLBarcode.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 16, 0, 0);
        jPGBLCatagory.add(jLBarcode, gridBagConstraints);

        jTBarcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTBarcode.setText("1012132240121");
        jTBarcode.setMaximumSize(new java.awt.Dimension(210, 21));
        jTBarcode.setMinimumSize(new java.awt.Dimension(210, 21));
        jTBarcode.setName("jTBarcode"); // NOI18N
        jTBarcode.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 0, 0);
        jPGBLCatagory.add(jTBarcode, gridBagConstraints);

        jLBrandName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLBrandName.setForeground(new java.awt.Color(15, 101, 220));
        jLBrandName.setText("Thương Hiệu");
        jLBrandName.setMaximumSize(new java.awt.Dimension(80, 15));
        jLBrandName.setMinimumSize(new java.awt.Dimension(80, 15));
        jLBrandName.setName("jLBrandName"); // NOI18N
        jLBrandName.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 128, 0, 0);
        jPGBLCatagory.add(jLBrandName, gridBagConstraints);

        jCbBrandName.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbBrandName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aimless", "M by Moda Mundo" }));
        jCbBrandName.setMaximumSize(new java.awt.Dimension(210, 21));
        jCbBrandName.setMinimumSize(new java.awt.Dimension(210, 21));
        jCbBrandName.setName("jCbBrandName"); // NOI18N
        jCbBrandName.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 0, 68);
        jPGBLCatagory.add(jCbBrandName, gridBagConstraints);

        jLSex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLSex.setForeground(new java.awt.Color(15, 101, 220));
        jLSex.setText("Giới Tính");
        jLSex.setMaximumSize(new java.awt.Dimension(80, 15));
        jLSex.setMinimumSize(new java.awt.Dimension(80, 15));
        jLSex.setName("jLSex"); // NOI18N
        jLSex.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        jPGBLCatagory.add(jLSex, gridBagConstraints);

        jCbSex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nữ", "Nam" }));
        jCbSex.setMaximumSize(new java.awt.Dimension(105, 21));
        jCbSex.setMinimumSize(new java.awt.Dimension(105, 21));
        jCbSex.setName("jCbSex"); // NOI18N
        jCbSex.setPreferredSize(new java.awt.Dimension(105, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        jPGBLCatagory.add(jCbSex, gridBagConstraints);

        jLCatagory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCatagory.setForeground(new java.awt.Color(15, 101, 220));
        jLCatagory.setText("Nhóm Hàng");
        jLCatagory.setMaximumSize(new java.awt.Dimension(80, 15));
        jLCatagory.setMinimumSize(new java.awt.Dimension(80, 15));
        jLCatagory.setName("jLCatagory"); // NOI18N
        jLCatagory.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 128, 0, 0);
        jPGBLCatagory.add(jLCatagory, gridBagConstraints);

        jCbCatagory.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbCatagory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apparel", "Underwear" }));
        jCbCatagory.setMaximumSize(new java.awt.Dimension(210, 21));
        jCbCatagory.setMinimumSize(new java.awt.Dimension(210, 21));
        jCbCatagory.setName("jCbCatagory"); // NOI18N
        jCbCatagory.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 68);
        jPGBLCatagory.add(jCbCatagory, gridBagConstraints);

        jLSeason.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLSeason.setForeground(new java.awt.Color(15, 101, 220));
        jLSeason.setText("Mùa");
        jLSeason.setMaximumSize(new java.awt.Dimension(80, 15));
        jLSeason.setMinimumSize(new java.awt.Dimension(80, 15));
        jLSeason.setName("jLSeason"); // NOI18N
        jLSeason.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        jPGBLCatagory.add(jLSeason, gridBagConstraints);

        jCbSeason.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCbSeason.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Xuân", "Hạ", "Thu", "Đông" }));
        jCbSeason.setMaximumSize(new java.awt.Dimension(105, 21));
        jCbSeason.setMinimumSize(new java.awt.Dimension(105, 21));
        jCbSeason.setName("jCbSeason"); // NOI18N
        jCbSeason.setPreferredSize(new java.awt.Dimension(105, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 33, 0);
        jPGBLCatagory.add(jCbSeason, gridBagConstraints);

        jLYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLYear.setForeground(new java.awt.Color(15, 101, 220));
        jLYear.setText("Năm");
        jLYear.setMaximumSize(new java.awt.Dimension(80, 15));
        jLYear.setMinimumSize(new java.awt.Dimension(80, 15));
        jLYear.setName("jLYear"); // NOI18N
        jLYear.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 128, 0, 0);
        jPGBLCatagory.add(jLYear, gridBagConstraints);

        jTYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTYear.setText("2011");
        jTYear.setMaximumSize(new java.awt.Dimension(105, 21));
        jTYear.setMinimumSize(new java.awt.Dimension(105, 21));
        jTYear.setName("jTYear"); // NOI18N
        jTYear.setPreferredSize(new java.awt.Dimension(105, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 33, 0);
        jPGBLCatagory.add(jTYear, gridBagConstraints);

        jPBLMiddle.add(jPGBLCatagory, java.awt.BorderLayout.CENTER);

        jPFLSub.add(jPBLMiddle);

        jPBLBottom.setBackground(new java.awt.Color(204, 204, 204));
        jPBLBottom.setMaximumSize(new java.awt.Dimension(800, 113));
        jPBLBottom.setMinimumSize(new java.awt.Dimension(800, 113));
        jPBLBottom.setName("jPBLBottom"); // NOI18N
        jPBLBottom.setPreferredSize(new java.awt.Dimension(800, 113));
        jPBLBottom.setLayout(new java.awt.BorderLayout());

        jPGBLAttribute.setBackground(new java.awt.Color(182, 214, 255));
        jPGBLAttribute.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thuộc Tính", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPGBLAttribute.setMaximumSize(new java.awt.Dimension(800, 113));
        jPGBLAttribute.setName("jPGBLAttribute"); // NOI18N
        jPGBLAttribute.setRequestFocusEnabled(false);
        jPGBLAttribute.setLayout(new java.awt.GridBagLayout());

        jLProductType.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLProductType.setForeground(new java.awt.Color(15, 101, 220));
        jLProductType.setText("Kiểu");
        jLProductType.setAlignmentY(0.0F);
        jLProductType.setMaximumSize(new java.awt.Dimension(80, 15));
        jLProductType.setMinimumSize(new java.awt.Dimension(80, 15));
        jLProductType.setName("jLProductType"); // NOI18N
        jLProductType.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 16, 0, 0);
        jPGBLAttribute.add(jLProductType, gridBagConstraints);

        jCbProductType.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbProductType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "T-shirt 02", "Brief 01", "Brief 02", "T-shirt 01" }));
        jCbProductType.setAlignmentY(0.0F);
        jCbProductType.setMaximumSize(new java.awt.Dimension(210, 21));
        jCbProductType.setMinimumSize(new java.awt.Dimension(210, 21));
        jCbProductType.setName("jCbProductType"); // NOI18N
        jCbProductType.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 0, 0);
        jPGBLAttribute.add(jCbProductType, gridBagConstraints);

        jLProductSize.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLProductSize.setForeground(new java.awt.Color(15, 101, 220));
        jLProductSize.setText("Kích Cỡ");
        jLProductSize.setAlignmentY(0.0F);
        jLProductSize.setMaximumSize(new java.awt.Dimension(80, 15));
        jLProductSize.setMinimumSize(new java.awt.Dimension(80, 15));
        jLProductSize.setName("jLProductSize"); // NOI18N
        jLProductSize.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        jPGBLAttribute.add(jLProductSize, gridBagConstraints);

        jCbProductSize.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbProductSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "L" }));
        jCbProductSize.setAlignmentY(0.0F);
        jCbProductSize.setMaximumSize(new java.awt.Dimension(105, 21));
        jCbProductSize.setMinimumSize(new java.awt.Dimension(105, 21));
        jCbProductSize.setName("jCbProductSize"); // NOI18N
        jCbProductSize.setPreferredSize(new java.awt.Dimension(105, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 32, 0);
        jPGBLAttribute.add(jCbProductSize, gridBagConstraints);

        jLProductColor.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLProductColor.setForeground(new java.awt.Color(15, 101, 220));
        jLProductColor.setText("Màu");
        jLProductColor.setAlignmentY(0.0F);
        jLProductColor.setMaximumSize(new java.awt.Dimension(80, 15));
        jLProductColor.setMinimumSize(new java.awt.Dimension(80, 15));
        jLProductColor.setName("jLProductColor"); // NOI18N
        jLProductColor.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 128, 0, 0);
        jPGBLAttribute.add(jLProductColor, gridBagConstraints);

        jCbProductColor.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbProductColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caro sọc Hồng", "Trắng", "Xám mel", "Caro sọc xanh" }));
        jCbProductColor.setAlignmentY(0.0F);
        jCbProductColor.setMaximumSize(new java.awt.Dimension(105, 21));
        jCbProductColor.setMinimumSize(new java.awt.Dimension(105, 21));
        jCbProductColor.setName("jCbProductColor"); // NOI18N
        jCbProductColor.setPreferredSize(new java.awt.Dimension(105, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 32, 0);
        jPGBLAttribute.add(jCbProductColor, gridBagConstraints);

        jLCollection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCollection.setForeground(new java.awt.Color(15, 101, 220));
        jLCollection.setText("Bộ Sưu Tập");
        jLCollection.setAlignmentY(0.0F);
        jLCollection.setMaximumSize(new java.awt.Dimension(80, 15));
        jLCollection.setMinimumSize(new java.awt.Dimension(80, 15));
        jLCollection.setName("jLCollection"); // NOI18N
        jLCollection.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 128, 0, 0);
        jPGBLAttribute.add(jLCollection, gridBagConstraints);

        jCbCollection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCbCollection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Modern", "Strech series" }));
        jCbCollection.setAlignmentY(0.0F);
        jCbCollection.setMaximumSize(new java.awt.Dimension(210, 21));
        jCbCollection.setMinimumSize(new java.awt.Dimension(210, 21));
        jCbCollection.setName("jCbCollection"); // NOI18N
        jCbCollection.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 0, 68);
        jPGBLAttribute.add(jCbCollection, gridBagConstraints);

        jPBLBottom.add(jPGBLAttribute, java.awt.BorderLayout.CENTER);

        jPFLSub.add(jPBLBottom);

        jPBLEnd.setBackground(new java.awt.Color(204, 204, 204));
        jPBLEnd.setMaximumSize(new java.awt.Dimension(800, 75));
        jPBLEnd.setMinimumSize(new java.awt.Dimension(800, 75));
        jPBLEnd.setName("jPBLEnd"); // NOI18N
        jPBLEnd.setPreferredSize(new java.awt.Dimension(800, 75));
        jPBLEnd.setLayout(new java.awt.BorderLayout());

        jPGBLReference.setBackground(new java.awt.Color(182, 214, 255));
        jPGBLReference.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tham Khảo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPGBLReference.setMaximumSize(new java.awt.Dimension(800, 75));
        jPGBLReference.setName("jPGBLReference"); // NOI18N
        jPGBLReference.setLayout(new java.awt.GridBagLayout());

        jLMaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLMaterial.setText("Chất Liệu");
        jLMaterial.setAlignmentY(0.0F);
        jLMaterial.setMaximumSize(new java.awt.Dimension(80, 15));
        jLMaterial.setMinimumSize(new java.awt.Dimension(80, 15));
        jLMaterial.setName("jLMaterial"); // NOI18N
        jLMaterial.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 16, 0, 0);
        jPGBLReference.add(jLMaterial, gridBagConstraints);

        jCbMaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCbMaterial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CVC", "92% cotton 8% spandex", "100% cotton" }));
        jCbMaterial.setAlignmentY(0.0F);
        jCbMaterial.setMaximumSize(new java.awt.Dimension(210, 21));
        jCbMaterial.setMinimumSize(new java.awt.Dimension(210, 21));
        jCbMaterial.setName("jCbMaterial"); // NOI18N
        jCbMaterial.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 33, 0);
        jPGBLReference.add(jCbMaterial, gridBagConstraints);

        jLType.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLType.setText("Loại");
        jLType.setAlignmentY(0.0F);
        jLType.setMaximumSize(new java.awt.Dimension(80, 15));
        jLType.setMinimumSize(new java.awt.Dimension(80, 15));
        jLType.setName("jLType"); // NOI18N
        jLType.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 129, 0, 0);
        jPGBLReference.add(jLType, gridBagConstraints);

        jCbType.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Top", "Bottom" }));
        jCbType.setAlignmentY(0.0F);
        jCbType.setMaximumSize(new java.awt.Dimension(210, 21));
        jCbType.setMinimumSize(new java.awt.Dimension(210, 21));
        jCbType.setName("jCbType"); // NOI18N
        jCbType.setPreferredSize(new java.awt.Dimension(210, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 33, 67);
        jPGBLReference.add(jCbType, gridBagConstraints);

        jPBLEnd.add(jPGBLReference, java.awt.BorderLayout.CENTER);

        jPFLSub.add(jPBLEnd);

        jPBLMain.add(jPFLSub, java.awt.BorderLayout.CENTER);

        jPanel.add(jPBLMain, "card2");

        add(jPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCbActive;
    private javax.swing.JComboBox jCbBrandName;
    private javax.swing.JComboBox jCbCatagory;
    private javax.swing.JComboBox jCbCollection;
    private javax.swing.JComboBox jCbMaterial;
    private javax.swing.JComboBox jCbProductColor;
    private javax.swing.JComboBox jCbProductSize;
    private javax.swing.JComboBox jCbProductType;
    private javax.swing.JComboBox jCbSeason;
    private javax.swing.JComboBox jCbSex;
    private javax.swing.JComboBox jCbTax;
    private javax.swing.JComboBox jCbType;
    private javax.swing.JComboBox jCbUnit;
    private javax.swing.JLabel jLActive;
    private javax.swing.JLabel jLBarcode;
    private javax.swing.JLabel jLBrandName;
    private javax.swing.JLabel jLCatagory;
    private javax.swing.JLabel jLCollection;
    private javax.swing.JLabel jLDescription;
    private javax.swing.JLabel jLMaterial;
    private javax.swing.JLabel jLProductColor;
    private javax.swing.JLabel jLProductID;
    private javax.swing.JLabel jLProductImage;
    private javax.swing.JLabel jLProductName;
    private javax.swing.JLabel jLProductSize;
    private javax.swing.JLabel jLProductType;
    private javax.swing.JLabel jLSeason;
    private javax.swing.JLabel jLSex;
    private javax.swing.JLabel jLTax;
    private javax.swing.JLabel jLType;
    private javax.swing.JLabel jLUnit;
    private javax.swing.JLabel jLYear;
    private javax.swing.JPanel jPBLBottom;
    private javax.swing.JPanel jPBLEnd;
    private javax.swing.JPanel jPBLMain;
    private javax.swing.JPanel jPBLMiddle;
    private javax.swing.JPanel jPBLTop;
    private javax.swing.JPanel jPFLSub;
    private javax.swing.JPanel jPGBLAttribute;
    private javax.swing.JPanel jPGBLCatagory;
    private javax.swing.JPanel jPGBLProduct;
    private javax.swing.JPanel jPGBLReference;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTBarcode;
    private javax.swing.JTextField jTDescription;
    private javax.swing.JTextField jTProductID;
    private javax.swing.JTextField jTProductName;
    private javax.swing.JTextField jTYear;
    // End of variables declaration//GEN-END:variables

}
