/**
 * Copyright: Copyright (c) 2009-2010 SunflowerVN, Co., Ltd. All rights reserved.
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF SunflowerVN, Co., Ltd. The 
 * copyright notice above does not evidence any actual or intended
 * publication of such source code.
 *
 * Description: 
 *
 * @author: www.sunflowervn.vn
 * @version: 1.0
 * @DateTime: Mar 20, 2009, 4:35:00 PM
 */
package vn.smartbiz.pos.sales.restaurant;

/**
 *
 * @author www.sunflowervn.vn
 */
public class JTicketsBagePOSTouchMap extends javax.swing.JPanel {

    /** Creates new form NewJPanelTest */
    public JTicketsBagePOSTouchMap() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPMain = new javax.swing.JPanel();
        jPSub = new javax.swing.JPanel();
        jPTop = new javax.swing.JPanel();
        jBCustomerWalk = new javax.swing.JButton();
        jBProduct = new javax.swing.JButton();
        jBAppointment = new javax.swing.JButton();
        jBCreditCard = new javax.swing.JButton();
        jBService = new javax.swing.JButton();
        jBDailyReport = new javax.swing.JButton();
        jPCenter = new javax.swing.JPanel();
        javax.swing.JLabel jBLogo = new javax.swing.JLabel();
        javax.swing.JLabel jBStoreName = new javax.swing.JLabel();
        jBTextMessage = new javax.swing.JButton();
        jBeMarketing = new javax.swing.JButton();
        jBGiftCard = new javax.swing.JButton();
        jBMembership = new javax.swing.JButton();
        jBAnnouceent = new javax.swing.JButton();
        jBMasterCard = new javax.swing.JButton();
        jBVisa = new javax.swing.JButton();
        jPBottom = new javax.swing.JPanel();
        jBCustomer = new javax.swing.JButton();
        jBOpenCashDrawer = new javax.swing.JButton();
        jBBackOffice = new javax.swing.JButton();
        jBLock = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(850, 650));
        setMinimumSize(new java.awt.Dimension(850, 650));
        setPreferredSize(new java.awt.Dimension(850, 650));
        setLayout(new java.awt.CardLayout());

        jPMain.setMaximumSize(new java.awt.Dimension(852, 614));
        jPMain.setMinimumSize(new java.awt.Dimension(852, 614));
        jPMain.setName("jPMain"); // NOI18N
        jPMain.setPreferredSize(new java.awt.Dimension(852, 614));
        jPMain.setLayout(new java.awt.BorderLayout());

        jPSub.setMaximumSize(new java.awt.Dimension(825, 602));
        jPSub.setMinimumSize(new java.awt.Dimension(825, 602));
        jPSub.setName("jPSub"); // NOI18N

        jPTop.setAlignmentX(0.0F);
        jPTop.setMaximumSize(new java.awt.Dimension(815, 160));
        jPTop.setMinimumSize(new java.awt.Dimension(815, 160));
        jPTop.setName("jPTop"); // NOI18N
        jPTop.setPreferredSize(new java.awt.Dimension(815, 160));
        jPTop.setLayout(new java.awt.GridBagLayout());

        jBCustomerWalk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Customer-Walk-in-list.png.png"))); // NOI18N
        jBCustomerWalk.setAutoscrolls(true);
        jBCustomerWalk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBCustomerWalk.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBCustomerWalk.setName("jBCustomerWalk"); // NOI18N
        jBCustomerWalk.setPreferredSize(new java.awt.Dimension(176, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPTop.add(jBCustomerWalk, gridBagConstraints);

        jBProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Product.png"))); // NOI18N
        jBProduct.setAutoscrolls(true);
        jBProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBProduct.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBProduct.setName("jBProduct"); // NOI18N
        jBProduct.setPreferredSize(new java.awt.Dimension(176, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPTop.add(jBProduct, gridBagConstraints);

        jBAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Appointment.png"))); // NOI18N
        jBAppointment.setAutoscrolls(true);
        jBAppointment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBAppointment.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBAppointment.setMaximumSize(new java.awt.Dimension(176, 160));
        jBAppointment.setMinimumSize(new java.awt.Dimension(176, 160));
        jBAppointment.setName("jBAppointment"); // NOI18N
        jBAppointment.setPreferredSize(new java.awt.Dimension(176, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPTop.add(jBAppointment, gridBagConstraints);

        jBCreditCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Credit-Card.png"))); // NOI18N
        jBCreditCard.setAutoscrolls(true);
        jBCreditCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBCreditCard.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBCreditCard.setName("jBCreditCard"); // NOI18N
        jBCreditCard.setPreferredSize(new java.awt.Dimension(155, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPTop.add(jBCreditCard, gridBagConstraints);

        jBService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Service.png"))); // NOI18N
        jBService.setAutoscrolls(true);
        jBService.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBService.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBService.setName("jBService"); // NOI18N
        jBService.setPreferredSize(new java.awt.Dimension(176, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -3;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPTop.add(jBService, gridBagConstraints);

        jBDailyReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Daily-Report.png"))); // NOI18N
        jBDailyReport.setAutoscrolls(true);
        jBDailyReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBDailyReport.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBDailyReport.setName("jBDailyReport"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -2;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 8);
        jPTop.add(jBDailyReport, gridBagConstraints);

        jPSub.add(jPTop);

        jPCenter.setAlignmentX(0.0F);
        jPCenter.setAlignmentY(0.0F);
        jPCenter.setMaximumSize(new java.awt.Dimension(810, 271));
        jPCenter.setMinimumSize(new java.awt.Dimension(810, 271));
        jPCenter.setName("jPCenter"); // NOI18N
        jPCenter.setPreferredSize(new java.awt.Dimension(810, 271));

        jBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Logo.png"))); // NOI18N
        jBLogo.setAlignmentY(0.0F);
        jBLogo.setName("jBLogo"); // NOI18N
        jBLogo.setPreferredSize(new java.awt.Dimension(440, 66));
        jBLogo.setVerifyInputWhenFocusTarget(false);

        jBStoreName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Sologan.png"))); // NOI18N
        jBStoreName.setAlignmentY(0.0F);
        jBStoreName.setName("jBStoreName"); // NOI18N
        jBStoreName.setVerifyInputWhenFocusTarget(false);

        jBTextMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Text-Message.png"))); // NOI18N
        jBTextMessage.setAutoscrolls(true);
        jBTextMessage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBTextMessage.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBTextMessage.setName("jBTextMessage"); // NOI18N
        jBTextMessage.setPreferredSize(new java.awt.Dimension(156, 133));

        jBeMarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/eMarketing.png"))); // NOI18N
        jBeMarketing.setAutoscrolls(true);
        jBeMarketing.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBeMarketing.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBeMarketing.setName("jBeMarketing"); // NOI18N
        jBeMarketing.setPreferredSize(new java.awt.Dimension(156, 131));

        jBGiftCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Gift-card.png"))); // NOI18N
        jBGiftCard.setAutoscrolls(true);
        jBGiftCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBGiftCard.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBGiftCard.setName("jBGiftCard"); // NOI18N
        jBGiftCard.setPreferredSize(new java.awt.Dimension(176, 160));

        jBMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Membership.png"))); // NOI18N
        jBMembership.setAutoscrolls(true);
        jBMembership.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBMembership.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBMembership.setName("jBMembership"); // NOI18N
        jBMembership.setPreferredSize(new java.awt.Dimension(176, 160));

        jBAnnouceent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Annoucement.png"))); // NOI18N
        jBAnnouceent.setAutoscrolls(true);
        jBAnnouceent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBAnnouceent.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBAnnouceent.setName("jBAnnouceent"); // NOI18N
        jBAnnouceent.setPreferredSize(new java.awt.Dimension(176, 160));

        jBMasterCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Mastercard.png"))); // NOI18N
        jBMasterCard.setAutoscrolls(true);
        jBMasterCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBMasterCard.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBMasterCard.setName("jBMasterCard"); // NOI18N
        jBMasterCard.setPreferredSize(new java.awt.Dimension(176, 160));

        jBVisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Visa.png"))); // NOI18N
        jBVisa.setAlignmentY(0.0F);
        jBVisa.setAutoscrolls(true);
        jBVisa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBVisa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBVisa.setName("jBVisa"); // NOI18N
        jBVisa.setPreferredSize(new java.awt.Dimension(176, 160));

        javax.swing.GroupLayout jPCenterLayout = new javax.swing.GroupLayout(jPCenter);
        jPCenter.setLayout(jPCenterLayout);
        jPCenterLayout.setHorizontalGroup(
            jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCenterLayout.createSequentialGroup()
                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBTextMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBeMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBAnnouceent, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBGiftCard, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPCenterLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCenterLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                            .addComponent(jBMasterCard, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(jPCenterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBStoreName)
                        .addContainerGap())))
        );
        jPCenterLayout.setVerticalGroup(
            jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCenterLayout.createSequentialGroup()
                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCenterLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCenterLayout.createSequentialGroup()
                                .addComponent(jBTextMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBeMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCenterLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jBStoreName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBMasterCard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPCenterLayout.createSequentialGroup()
                        .addComponent(jBGiftCard, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAnnouceent, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
            .addGroup(jPCenterLayout.createSequentialGroup()
                .addComponent(jBLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPSub.add(jPCenter);

        jPBottom.setAlignmentX(0.0F);
        jPBottom.setAlignmentY(0.0F);
        jPBottom.setName("jPBottom"); // NOI18N
        jPBottom.setLayout(new java.awt.GridBagLayout());

        jBCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Customer.png"))); // NOI18N
        jBCustomer.setAutoscrolls(true);
        jBCustomer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBCustomer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBCustomer.setName("jBCustomer"); // NOI18N
        jBCustomer.setPreferredSize(new java.awt.Dimension(156, 160));
        jPBottom.add(jBCustomer, new java.awt.GridBagConstraints());

        jBOpenCashDrawer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Open-Cash-Drawer.png"))); // NOI18N
        jBOpenCashDrawer.setAutoscrolls(true);
        jBOpenCashDrawer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBOpenCashDrawer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBOpenCashDrawer.setName("jBOpenCashDrawer"); // NOI18N
        jBOpenCashDrawer.setPreferredSize(new java.awt.Dimension(176, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPBottom.add(jBOpenCashDrawer, gridBagConstraints);

        jBBackOffice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Back-Office.png"))); // NOI18N
        jBBackOffice.setAutoscrolls(true);
        jBBackOffice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBBackOffice.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBBackOffice.setName("jBBackOffice"); // NOI18N
        jBBackOffice.setPreferredSize(new java.awt.Dimension(176, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -21;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPBottom.add(jBBackOffice, gridBagConstraints);

        jBLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Lock.png"))); // NOI18N
        jBLock.setAutoscrolls(true);
        jBLock.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBLock.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBLock.setName("jBLock"); // NOI18N
        jBLock.setPreferredSize(new java.awt.Dimension(176, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -20;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPBottom.add(jBLock, gridBagConstraints);

        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/smartbiz/images/epostouch/Exit.png"))); // NOI18N
        jBExit.setAutoscrolls(true);
        jBExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBExit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBExit.setName("jBExit"); // NOI18N
        jBExit.setPreferredSize(new java.awt.Dimension(176, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPBottom.add(jBExit, gridBagConstraints);

        jPSub.add(jPBottom);

        jPMain.add(jPSub, java.awt.BorderLayout.CENTER);

        add(jPMain, "card2");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnnouceent;
    private javax.swing.JButton jBAppointment;
    private javax.swing.JButton jBBackOffice;
    private javax.swing.JButton jBCreditCard;
    private javax.swing.JButton jBCustomer;
    private javax.swing.JButton jBCustomerWalk;
    private javax.swing.JButton jBDailyReport;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBGiftCard;
    private javax.swing.JButton jBLock;
    private javax.swing.JButton jBMasterCard;
    private javax.swing.JButton jBMembership;
    private javax.swing.JButton jBOpenCashDrawer;
    private javax.swing.JButton jBProduct;
    private javax.swing.JButton jBService;
    private javax.swing.JButton jBTextMessage;
    private javax.swing.JButton jBVisa;
    private javax.swing.JButton jBeMarketing;
    private javax.swing.JPanel jPBottom;
    private javax.swing.JPanel jPCenter;
    private javax.swing.JPanel jPMain;
    private javax.swing.JPanel jPSub;
    private javax.swing.JPanel jPTop;
    // End of variables declaration//GEN-END:variables
}
