/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestLayout1.java
 *
 * Created on Jul 13, 2011, 2:07:41 PM
 */

package vn.smartbiz.pos.registration;

/**
 *
 * @author Administrator
 */
public class JRegistration extends javax.swing.JPanel {

    /** Creates new form TestLayout1 */
    public JRegistration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel = new javax.swing.JPanel();
        jPMain = new javax.swing.JPanel();
        jPSub = new javax.swing.JPanel();
        jPTop = new javax.swing.JPanel();
        jPLocation = new javax.swing.JPanel();
        jLStoreName = new javax.swing.JLabel();
        jLAddress = new javax.swing.JLabel();
        jLCountry = new javax.swing.JLabel();
        jTStoreName = new javax.swing.JTextField();
        jBStoreName = new javax.swing.JButton();
        jTAddress = new javax.swing.JTextField();
        jBAddress = new javax.swing.JButton();
        jCbCountry = new javax.swing.JComboBox();
        jLCity = new javax.swing.JLabel();
        jCbCity = new javax.swing.JComboBox();
        jLState = new javax.swing.JLabel();
        jCbState = new javax.swing.JComboBox();
        jLZip = new javax.swing.JLabel();
        jTZip = new javax.swing.JTextField();
        jBZip = new javax.swing.JButton();
        jPMiddle = new javax.swing.JPanel();
        jPContact = new javax.swing.JPanel();
        jLEmail = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jBEmail = new javax.swing.JButton();
        jLPhone = new javax.swing.JLabel();
        jTPhone = new javax.swing.JTextField();
        jBPhone = new javax.swing.JButton();
        jLFax = new javax.swing.JLabel();
        jTFax = new javax.swing.JTextField();
        jBFax = new javax.swing.JButton();
        jLProductID = new javax.swing.JLabel();
        jTProductID1 = new javax.swing.JTextField();
        jBProductID1 = new javax.swing.JButton();
        jTProductID2 = new javax.swing.JTextField();
        jBProductID2 = new javax.swing.JButton();
        jTProductID3 = new javax.swing.JTextField();
        jBProductID3 = new javax.swing.JButton();
        jTProductID4 = new javax.swing.JTextField();
        jBProductID4 = new javax.swing.JButton();
        jTProductID5 = new javax.swing.JTextField();
        jBProductID5 = new javax.swing.JButton();
        jPBottom = new javax.swing.JPanel();
        jPCommand = new javax.swing.JPanel();
        jBRegister = new javax.swing.JButton();
        jBTrial = new javax.swing.JButton();
        jBClose = new javax.swing.JButton();
        jPRegister = new javax.swing.JPanel();
        jRbRegisterOnline = new javax.swing.JRadioButton();
        jRbRegisterPhone = new javax.swing.JRadioButton();
        jLSerialNumber = new javax.swing.JLabel();
        jTSerialNumber1 = new javax.swing.JTextField();
        jTSerialNumber2 = new javax.swing.JTextField();
        jTSerialNumber3 = new javax.swing.JTextField();
        jLKey = new javax.swing.JLabel();
        jTKey1 = new javax.swing.JTextField();
        jTKey2 = new javax.swing.JTextField();
        jTKey3 = new javax.swing.JTextField();
        jLExpired = new javax.swing.JLabel();
        jBKey1 = new javax.swing.JButton();
        jBKey2 = new javax.swing.JButton();
        jBKey3 = new javax.swing.JButton();
        jLKey1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.CardLayout());

        jPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel.setName("jPanel"); // NOI18N
        jPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel.setLayout(new java.awt.CardLayout());

        jPMain.setMaximumSize(new java.awt.Dimension(800, 600));
        jPMain.setMinimumSize(new java.awt.Dimension(800, 600));
        jPMain.setName("jPMain"); // NOI18N
        jPMain.setPreferredSize(new java.awt.Dimension(800, 600));
        jPMain.setLayout(new java.awt.BorderLayout());

        jPSub.setBackground(new java.awt.Color(255, 255, 255));
        jPSub.setMaximumSize(new java.awt.Dimension(800, 600));
        jPSub.setMinimumSize(new java.awt.Dimension(800, 600));
        jPSub.setName("jPSub"); // NOI18N
        jPSub.setPreferredSize(new java.awt.Dimension(800, 600));

        jPTop.setBackground(new java.awt.Color(204, 204, 204));
        jPTop.setMaximumSize(new java.awt.Dimension(800, 165));
        jPTop.setMinimumSize(new java.awt.Dimension(800, 165));
        jPTop.setName("jPTop"); // NOI18N
        jPTop.setPreferredSize(new java.awt.Dimension(800, 165));
        jPTop.setLayout(new java.awt.BorderLayout());

        jPLocation.setBackground(new java.awt.Color(255, 255, 255));
        jPLocation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPLocation.setMaximumSize(new java.awt.Dimension(800, 165));
        jPLocation.setMinimumSize(new java.awt.Dimension(800, 165));
        jPLocation.setName("jPLocation"); // NOI18N

        jLStoreName.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLStoreName.setForeground(new java.awt.Color(0, 112, 197));
        jLStoreName.setText("Store Name");
        jLStoreName.setName("jLStoreName"); // NOI18N

        jLAddress.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLAddress.setText("Address");
        jLAddress.setMaximumSize(new java.awt.Dimension(71, 15));
        jLAddress.setMinimumSize(new java.awt.Dimension(71, 15));
        jLAddress.setName("jLAddress"); // NOI18N
        jLAddress.setPreferredSize(new java.awt.Dimension(71, 15));

        jLCountry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCountry.setText("Country");
        jLCountry.setMaximumSize(new java.awt.Dimension(71, 15));
        jLCountry.setMinimumSize(new java.awt.Dimension(71, 15));
        jLCountry.setName("jLCountry"); // NOI18N
        jLCountry.setPreferredSize(new java.awt.Dimension(71, 15));

        jTStoreName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTStoreName.setText("La Belle Nail Spa"); // NOI18N
        jTStoreName.setMaximumSize(new java.awt.Dimension(630, 21));
        jTStoreName.setMinimumSize(new java.awt.Dimension(630, 21));
        jTStoreName.setName("jTStoreName"); // NOI18N
        jTStoreName.setPreferredSize(new java.awt.Dimension(630, 21));

        jBStoreName.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBStoreName.setText("StoreName");
        jBStoreName.setMaximumSize(new java.awt.Dimension(32, 32));
        jBStoreName.setMinimumSize(new java.awt.Dimension(32, 32));
        jBStoreName.setName("jBStoreName"); // NOI18N
        jBStoreName.setPreferredSize(new java.awt.Dimension(32, 32));

        jTAddress.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTAddress.setText("123 Lovely Land"); // NOI18N
        jTAddress.setMaximumSize(new java.awt.Dimension(630, 21));
        jTAddress.setMinimumSize(new java.awt.Dimension(630, 21));
        jTAddress.setName("jTAddress"); // NOI18N
        jTAddress.setPreferredSize(new java.awt.Dimension(630, 21));

        jBAddress.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBAddress.setText("Address");
        jBAddress.setMaximumSize(new java.awt.Dimension(32, 32));
        jBAddress.setMinimumSize(new java.awt.Dimension(32, 32));
        jBAddress.setName("jBAddress"); // NOI18N
        jBAddress.setPreferredSize(new java.awt.Dimension(32, 32));

        jCbCountry.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "United States", "Item 2", "Item 3", "Item 4" }));
        jCbCountry.setMaximumSize(new java.awt.Dimension(200, 21));
        jCbCountry.setMinimumSize(new java.awt.Dimension(200, 21));
        jCbCountry.setName("jCbCountry"); // NOI18N
        jCbCountry.setPreferredSize(new java.awt.Dimension(200, 21));

        jLCity.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLCity.setText("City");
        jLCity.setMaximumSize(new java.awt.Dimension(71, 15));
        jLCity.setMinimumSize(new java.awt.Dimension(71, 15));
        jLCity.setName("jLCity"); // NOI18N
        jLCity.setPreferredSize(new java.awt.Dimension(71, 15));

        jCbCity.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Naperville", "Item 2", "Item 3", "Item 4" }));
        jCbCity.setMaximumSize(new java.awt.Dimension(200, 21));
        jCbCity.setMinimumSize(new java.awt.Dimension(200, 21));
        jCbCity.setName("jCbCity"); // NOI18N
        jCbCity.setPreferredSize(new java.awt.Dimension(200, 21));

        jLState.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLState.setText("State");
        jLState.setMaximumSize(new java.awt.Dimension(71, 15));
        jLState.setMinimumSize(new java.awt.Dimension(71, 15));
        jLState.setName("jLState"); // NOI18N
        jLState.setPreferredSize(new java.awt.Dimension(71, 15));

        jCbState.setFont(new java.awt.Font("Tahoma", 1, 12));
        jCbState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IL", "Item 2", "Item 3", "Item 4" }));
        jCbState.setMaximumSize(new java.awt.Dimension(200, 21));
        jCbState.setMinimumSize(new java.awt.Dimension(200, 21));
        jCbState.setName("jCbState"); // NOI18N
        jCbState.setPreferredSize(new java.awt.Dimension(200, 21));

        jLZip.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLZip.setText("Zip");
        jLZip.setMaximumSize(new java.awt.Dimension(71, 15));
        jLZip.setMinimumSize(new java.awt.Dimension(71, 15));
        jLZip.setName("jLZip"); // NOI18N
        jLZip.setPreferredSize(new java.awt.Dimension(71, 15));

        jTZip.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTZip.setText("60564");
        jTZip.setName("jTZip"); // NOI18N
        jTZip.setPreferredSize(new java.awt.Dimension(200, 21));

        jBZip.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBZip.setText("Zip");
        jBZip.setMaximumSize(new java.awt.Dimension(32, 32));
        jBZip.setMinimumSize(new java.awt.Dimension(32, 32));
        jBZip.setName("jBZip"); // NOI18N
        jBZip.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPLocationLayout = new javax.swing.GroupLayout(jPLocation);
        jPLocation.setLayout(jPLocationLayout);
        jPLocationLayout.setHorizontalGroup(
            jPLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLocationLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addComponent(jLStoreName)
                        .addGap(41, 41, 41)
                        .addComponent(jTStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addComponent(jLAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addComponent(jLCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jCbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addComponent(jLState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jCbState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPLocationLayout.setVerticalGroup(
            jPLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLocationLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLStoreName))
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jCbState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPLocationLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        jPTop.add(jPLocation, java.awt.BorderLayout.CENTER);

        jPSub.add(jPTop);

        jPMiddle.setBackground(new java.awt.Color(204, 204, 204));
        jPMiddle.setForeground(new java.awt.Color(204, 204, 204));
        jPMiddle.setMaximumSize(new java.awt.Dimension(800, 140));
        jPMiddle.setMinimumSize(new java.awt.Dimension(800, 140));
        jPMiddle.setName("jPMiddle"); // NOI18N
        jPMiddle.setPreferredSize(new java.awt.Dimension(800, 140));
        jPMiddle.setLayout(new java.awt.BorderLayout());

        jPContact.setBackground(new java.awt.Color(255, 255, 255));
        jPContact.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPContact.setMaximumSize(new java.awt.Dimension(800, 140));
        jPContact.setName("jPContact"); // NOI18N
        jPContact.setPreferredSize(new java.awt.Dimension(800, 140));
        jPContact.setRequestFocusEnabled(false);
        jPContact.setLayout(new java.awt.GridBagLayout());

        jLEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEmail.setForeground(new java.awt.Color(0, 112, 197));
        jLEmail.setText("Email");
        jLEmail.setMaximumSize(new java.awt.Dimension(71, 15));
        jLEmail.setMinimumSize(new java.awt.Dimension(71, 15));
        jLEmail.setName("jLEmail"); // NOI18N
        jLEmail.setPreferredSize(new java.awt.Dimension(71, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 12, 0, 0);
        jPContact.add(jLEmail, gridBagConstraints);

        jTEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTEmail.setText("Info@sunflowervn.vn");
        jTEmail.setName("jTEmail"); // NOI18N
        jTEmail.setPreferredSize(new java.awt.Dimension(630, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 625;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 0, 0);
        jPContact.add(jTEmail, gridBagConstraints);

        jBEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBEmail.setText("Email");
        jBEmail.setMaximumSize(new java.awt.Dimension(32, 32));
        jBEmail.setMinimumSize(new java.awt.Dimension(32, 32));
        jBEmail.setName("jBEmail"); // NOI18N
        jBEmail.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 5, 0, 8);
        jPContact.add(jBEmail, gridBagConstraints);

        jLPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLPhone.setForeground(new java.awt.Color(0, 112, 197));
        jLPhone.setText("Phone");
        jLPhone.setMaximumSize(new java.awt.Dimension(71, 15));
        jLPhone.setMinimumSize(new java.awt.Dimension(71, 15));
        jLPhone.setName("jLPhone"); // NOI18N
        jLPhone.setPreferredSize(new java.awt.Dimension(71, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 12, 0, 0);
        jPContact.add(jLPhone, gridBagConstraints);

        jTPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTPhone.setText("0908 20 30 80");
        jTPhone.setMaximumSize(new java.awt.Dimension(200, 21));
        jTPhone.setMinimumSize(new java.awt.Dimension(200, 21));
        jTPhone.setName("jTPhone"); // NOI18N
        jTPhone.setPreferredSize(new java.awt.Dimension(200, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 0, 0);
        jPContact.add(jTPhone, gridBagConstraints);

        jBPhone.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBPhone.setText("Phone");
        jBPhone.setMaximumSize(new java.awt.Dimension(32, 32));
        jBPhone.setMinimumSize(new java.awt.Dimension(32, 32));
        jBPhone.setName("jBPhone"); // NOI18N
        jBPhone.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 0);
        jPContact.add(jBPhone, gridBagConstraints);

        jLFax.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLFax.setForeground(new java.awt.Color(0, 112, 197));
        jLFax.setText("Fax");
        jLFax.setMaximumSize(new java.awt.Dimension(71, 15));
        jLFax.setMinimumSize(new java.awt.Dimension(71, 15));
        jLFax.setName("jLFax"); // NOI18N
        jLFax.setPreferredSize(new java.awt.Dimension(71, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 8, 0, 0);
        jPContact.add(jLFax, gridBagConstraints);

        jTFax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFax.setText("555-555-5555");
        jTFax.setMaximumSize(new java.awt.Dimension(200, 21));
        jTFax.setMinimumSize(new java.awt.Dimension(200, 21));
        jTFax.setName("jTFax"); // NOI18N
        jTFax.setPreferredSize(new java.awt.Dimension(200, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPContact.add(jTFax, gridBagConstraints);

        jBFax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBFax.setLabel("Fax");
        jBFax.setMaximumSize(new java.awt.Dimension(32, 32));
        jBFax.setMinimumSize(new java.awt.Dimension(32, 32));
        jBFax.setName("jBFax"); // NOI18N
        jBFax.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 8);
        jPContact.add(jBFax, gridBagConstraints);

        jLProductID.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLProductID.setForeground(new java.awt.Color(0, 112, 197));
        jLProductID.setText("Product ID");
        jLProductID.setMaximumSize(new java.awt.Dimension(71, 15));
        jLProductID.setMinimumSize(new java.awt.Dimension(71, 15));
        jLProductID.setName("jLProductID"); // NOI18N
        jLProductID.setPreferredSize(new java.awt.Dimension(71, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 12, 0, 0);
        jPContact.add(jLProductID, gridBagConstraints);

        jTProductID1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTProductID1.setMaximumSize(new java.awt.Dimension(70, 21));
        jTProductID1.setMinimumSize(new java.awt.Dimension(70, 21));
        jTProductID1.setName("jTProductID1"); // NOI18N
        jTProductID1.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 40, 0, 0);
        jPContact.add(jTProductID1, gridBagConstraints);

        jBProductID1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBProductID1.setText("ID1");
        jBProductID1.setMaximumSize(new java.awt.Dimension(32, 32));
        jBProductID1.setMinimumSize(new java.awt.Dimension(32, 32));
        jBProductID1.setName("jBProductID1"); // NOI18N
        jBProductID1.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 0);
        jPContact.add(jBProductID1, gridBagConstraints);

        jTProductID2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTProductID2.setMaximumSize(new java.awt.Dimension(70, 21));
        jTProductID2.setMinimumSize(new java.awt.Dimension(70, 21));
        jTProductID2.setName("jTProductID2"); // NOI18N
        jTProductID2.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 25, 0, 0);
        jPContact.add(jTProductID2, gridBagConstraints);

        jBProductID2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBProductID2.setText("ID2");
        jBProductID2.setMaximumSize(new java.awt.Dimension(32, 32));
        jBProductID2.setMinimumSize(new java.awt.Dimension(32, 32));
        jBProductID2.setName("jBProductID2"); // NOI18N
        jBProductID2.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 0);
        jPContact.add(jBProductID2, gridBagConstraints);

        jTProductID3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTProductID3.setMaximumSize(new java.awt.Dimension(70, 21));
        jTProductID3.setMinimumSize(new java.awt.Dimension(70, 21));
        jTProductID3.setName("jTProductID3"); // NOI18N
        jTProductID3.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 0, 0);
        jPContact.add(jTProductID3, gridBagConstraints);

        jBProductID3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBProductID3.setText("ID2");
        jBProductID3.setMaximumSize(new java.awt.Dimension(32, 32));
        jBProductID3.setMinimumSize(new java.awt.Dimension(32, 32));
        jBProductID3.setName("jBProductID3"); // NOI18N
        jBProductID3.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 0);
        jPContact.add(jBProductID3, gridBagConstraints);

        jTProductID4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTProductID4.setMaximumSize(new java.awt.Dimension(70, 21));
        jTProductID4.setMinimumSize(new java.awt.Dimension(70, 21));
        jTProductID4.setName("jTProductID4"); // NOI18N
        jTProductID4.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 22, 0, 0);
        jPContact.add(jTProductID4, gridBagConstraints);

        jBProductID4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBProductID4.setActionCommand("ID4");
        jBProductID4.setLabel("ID4");
        jBProductID4.setMaximumSize(new java.awt.Dimension(32, 32));
        jBProductID4.setMinimumSize(new java.awt.Dimension(32, 32));
        jBProductID4.setName("jBProductID4"); // NOI18N
        jBProductID4.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 0);
        jPContact.add(jBProductID4, gridBagConstraints);

        jTProductID5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTProductID5.setMaximumSize(new java.awt.Dimension(70, 21));
        jTProductID5.setMinimumSize(new java.awt.Dimension(70, 21));
        jTProductID5.setName("jTProductID5"); // NOI18N
        jTProductID5.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 22, 0, 0);
        jPContact.add(jTProductID5, gridBagConstraints);

        jBProductID5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBProductID5.setText("ID5");
        jBProductID5.setMaximumSize(new java.awt.Dimension(32, 32));
        jBProductID5.setMinimumSize(new java.awt.Dimension(32, 32));
        jBProductID5.setName("jBProductID5"); // NOI18N
        jBProductID5.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 0);
        jPContact.add(jBProductID5, gridBagConstraints);

        jPMiddle.add(jPContact, java.awt.BorderLayout.CENTER);

        jPSub.add(jPMiddle);

        jPBottom.setBackground(new java.awt.Color(204, 204, 204));
        jPBottom.setMaximumSize(new java.awt.Dimension(800, 284));
        jPBottom.setMinimumSize(new java.awt.Dimension(800, 284));
        jPBottom.setName("jPBottom"); // NOI18N
        jPBottom.setPreferredSize(new java.awt.Dimension(800, 284));
        jPBottom.setLayout(new java.awt.BorderLayout());

        jPCommand.setBackground(new java.awt.Color(255, 255, 255));
        jPCommand.setMaximumSize(new java.awt.Dimension(800, 32));
        jPCommand.setMinimumSize(new java.awt.Dimension(800, 32));
        jPCommand.setName("jPCommand"); // NOI18N
        jPCommand.setPreferredSize(new java.awt.Dimension(800, 32));
        jPCommand.setLayout(new java.awt.GridBagLayout());

        jBRegister.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBRegister.setText("Register");
        jBRegister.setMaximumSize(new java.awt.Dimension(108, 32));
        jBRegister.setMinimumSize(new java.awt.Dimension(108, 32));
        jBRegister.setName("jBRegister"); // NOI18N
        jBRegister.setPreferredSize(new java.awt.Dimension(110, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 164, 0, 0);
        jPCommand.add(jBRegister, gridBagConstraints);

        jBTrial.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBTrial.setText("Trial");
        jBTrial.setMaximumSize(new java.awt.Dimension(108, 32));
        jBTrial.setMinimumSize(new java.awt.Dimension(108, 32));
        jBTrial.setName("jBTrial"); // NOI18N
        jBTrial.setPreferredSize(new java.awt.Dimension(100, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 88, 0, 0);
        jPCommand.add(jBTrial, gridBagConstraints);

        jBClose.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBClose.setText("Close");
        jBClose.setMaximumSize(new java.awt.Dimension(108, 32));
        jBClose.setMinimumSize(new java.awt.Dimension(108, 32));
        jBClose.setName("jBClose"); // NOI18N
        jBClose.setPreferredSize(new java.awt.Dimension(100, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 90, 0, 152);
        jPCommand.add(jBClose, gridBagConstraints);

        jPBottom.add(jPCommand, java.awt.BorderLayout.PAGE_END);

        jPRegister.setBackground(new java.awt.Color(255, 255, 255));
        jPRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPRegister.setMaximumSize(new java.awt.Dimension(800, 252));
        jPRegister.setName("jPRegister"); // NOI18N
        jPRegister.setLayout(new java.awt.GridBagLayout());

        jRbRegisterOnline.setBackground(new java.awt.Color(255, 255, 255));
        jRbRegisterOnline.setFont(new java.awt.Font("Tahoma", 1, 12));
        jRbRegisterOnline.setSelected(true);
        jRbRegisterOnline.setText("Register Online");
        jRbRegisterOnline.setName("jRbRegisterOnline"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 0);
        jPRegister.add(jRbRegisterOnline, gridBagConstraints);

        jRbRegisterPhone.setBackground(new java.awt.Color(255, 255, 255));
        jRbRegisterPhone.setFont(new java.awt.Font("Tahoma", 1, 12));
        jRbRegisterPhone.setActionCommand("Register by Phone");
        jRbRegisterPhone.setLabel("Register by Phone");
        jRbRegisterPhone.setName("jRbRegisterPhone"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 8, 0, 0);
        jPRegister.add(jRbRegisterPhone, gridBagConstraints);

        jLSerialNumber.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLSerialNumber.setForeground(new java.awt.Color(0, 112, 197));
        jLSerialNumber.setText("Serial Number");
        jLSerialNumber.setMaximumSize(new java.awt.Dimension(71, 15));
        jLSerialNumber.setMinimumSize(new java.awt.Dimension(71, 15));
        jLSerialNumber.setName("jLSerialNumber"); // NOI18N
        jLSerialNumber.setPreferredSize(new java.awt.Dimension(71, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 57, 0, 0);
        jPRegister.add(jLSerialNumber, gridBagConstraints);

        jTSerialNumber1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTSerialNumber1.setText("BFEBF");
        jTSerialNumber1.setMaximumSize(new java.awt.Dimension(70, 21));
        jTSerialNumber1.setMinimumSize(new java.awt.Dimension(70, 21));
        jTSerialNumber1.setName("jTSerialNumber1"); // NOI18N
        jTSerialNumber1.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 62, 0, 0);
        jPRegister.add(jTSerialNumber1, gridBagConstraints);

        jTSerialNumber2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTSerialNumber2.setText("D3652");
        jTSerialNumber2.setMaximumSize(new java.awt.Dimension(70, 21));
        jTSerialNumber2.setMinimumSize(new java.awt.Dimension(70, 21));
        jTSerialNumber2.setName("jTSerialNumber2"); // NOI18N
        jTSerialNumber2.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 0);
        jPRegister.add(jTSerialNumber2, gridBagConstraints);

        jTSerialNumber3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTSerialNumber3.setText("74F06");
        jTSerialNumber3.setMaximumSize(new java.awt.Dimension(70, 21));
        jTSerialNumber3.setMinimumSize(new java.awt.Dimension(70, 21));
        jTSerialNumber3.setName("jTSerialNumber3"); // NOI18N
        jTSerialNumber3.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 0);
        jPRegister.add(jTSerialNumber3, gridBagConstraints);

        jLKey.setBackground(new java.awt.Color(255, 255, 255));
        jLKey.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLKey.setText("Write down your serial number, please contact our technical support 888-922-6766. We will"); // NOI18N
        jLKey.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLKey.setMaximumSize(new java.awt.Dimension(750, 30));
        jLKey.setMinimumSize(new java.awt.Dimension(750, 30));
        jLKey.setName("jLKey"); // NOI18N
        jLKey.setOpaque(true);
        jLKey.setPreferredSize(new java.awt.Dimension(750, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.ipady = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 36, 0, 14);
        jPRegister.add(jLKey, gridBagConstraints);

        jTKey1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTKey1.setMaximumSize(new java.awt.Dimension(70, 21));
        jTKey1.setMinimumSize(new java.awt.Dimension(70, 21));
        jTKey1.setName("jTKey1"); // NOI18N
        jTKey1.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 26, 0, 0);
        jPRegister.add(jTKey1, gridBagConstraints);

        jTKey2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTKey2.setMaximumSize(new java.awt.Dimension(70, 21));
        jTKey2.setMinimumSize(new java.awt.Dimension(70, 21));
        jTKey2.setName("jTKey2"); // NOI18N
        jTKey2.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 84, 0, 0);
        jPRegister.add(jTKey2, gridBagConstraints);

        jTKey3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTKey3.setMaximumSize(new java.awt.Dimension(70, 21));
        jTKey3.setMinimumSize(new java.awt.Dimension(70, 21));
        jTKey3.setName("jTKey3"); // NOI18N
        jTKey3.setPreferredSize(new java.awt.Dimension(70, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 0, 0);
        jPRegister.add(jTKey3, gridBagConstraints);

        jLExpired.setBackground(new java.awt.Color(255, 255, 255));
        jLExpired.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLExpired.setText("Your PCNails will expired in 3 days or 977 times\n"); // NOI18N
        jLExpired.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLExpired.setMaximumSize(new java.awt.Dimension(750, 30));
        jLExpired.setMinimumSize(new java.awt.Dimension(750, 30));
        jLExpired.setName("jLExpired"); // NOI18N
        jLExpired.setOpaque(true);
        jLExpired.setPreferredSize(new java.awt.Dimension(750, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = -437;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 6, 0);
        jPRegister.add(jLExpired, gridBagConstraints);

        jBKey1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBKey1.setText("Key1");
        jBKey1.setMaximumSize(new java.awt.Dimension(32, 32));
        jBKey1.setMinimumSize(new java.awt.Dimension(32, 32));
        jBKey1.setName("jBKey1"); // NOI18N
        jBKey1.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPRegister.add(jBKey1, gridBagConstraints);

        jBKey2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBKey2.setText("Key2");
        jBKey2.setMaximumSize(new java.awt.Dimension(32, 32));
        jBKey2.setMinimumSize(new java.awt.Dimension(32, 32));
        jBKey2.setName("jBKey2"); // NOI18N
        jBKey2.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPRegister.add(jBKey2, gridBagConstraints);

        jBKey3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBKey3.setText("Key3");
        jBKey3.setMaximumSize(new java.awt.Dimension(32, 32));
        jBKey3.setMinimumSize(new java.awt.Dimension(32, 32));
        jBKey3.setName("jBKey3"); // NOI18N
        jBKey3.setPreferredSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPRegister.add(jBKey3, gridBagConstraints);

        jLKey1.setBackground(new java.awt.Color(255, 255, 255));
        jLKey1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLKey1.setText("give you activation key, then enter here"); // NOI18N
        jLKey1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLKey1.setMaximumSize(new java.awt.Dimension(750, 30));
        jLKey1.setMinimumSize(new java.awt.Dimension(750, 30));
        jLKey1.setName("jLKey1"); // NOI18N
        jLKey1.setOpaque(true);
        jLKey1.setPreferredSize(new java.awt.Dimension(750, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.ipady = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 36, 0, 14);
        jPRegister.add(jLKey1, gridBagConstraints);

        jPBottom.add(jPRegister, java.awt.BorderLayout.CENTER);

        jPSub.add(jPBottom);

        jPMain.add(jPSub, java.awt.BorderLayout.CENTER);

        jPanel.add(jPMain, "card2");

        add(jPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddress;
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBEmail;
    private javax.swing.JButton jBFax;
    private javax.swing.JButton jBKey1;
    private javax.swing.JButton jBKey2;
    private javax.swing.JButton jBKey3;
    private javax.swing.JButton jBPhone;
    private javax.swing.JButton jBProductID1;
    private javax.swing.JButton jBProductID2;
    private javax.swing.JButton jBProductID3;
    private javax.swing.JButton jBProductID4;
    private javax.swing.JButton jBProductID5;
    private javax.swing.JButton jBRegister;
    private javax.swing.JButton jBStoreName;
    private javax.swing.JButton jBTrial;
    private javax.swing.JButton jBZip;
    private javax.swing.JComboBox jCbCity;
    private javax.swing.JComboBox jCbCountry;
    private javax.swing.JComboBox jCbState;
    private javax.swing.JLabel jLAddress;
    private javax.swing.JLabel jLCity;
    private javax.swing.JLabel jLCountry;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLExpired;
    private javax.swing.JLabel jLFax;
    private javax.swing.JLabel jLKey;
    private javax.swing.JLabel jLKey1;
    private javax.swing.JLabel jLPhone;
    private javax.swing.JLabel jLProductID;
    private javax.swing.JLabel jLSerialNumber;
    private javax.swing.JLabel jLState;
    private javax.swing.JLabel jLStoreName;
    private javax.swing.JLabel jLZip;
    private javax.swing.JPanel jPBottom;
    private javax.swing.JPanel jPCommand;
    private javax.swing.JPanel jPContact;
    private javax.swing.JPanel jPLocation;
    private javax.swing.JPanel jPMain;
    private javax.swing.JPanel jPMiddle;
    private javax.swing.JPanel jPRegister;
    private javax.swing.JPanel jPSub;
    private javax.swing.JPanel jPTop;
    private javax.swing.JPanel jPanel;
    private javax.swing.JRadioButton jRbRegisterOnline;
    private javax.swing.JRadioButton jRbRegisterPhone;
    private javax.swing.JTextField jTAddress;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTFax;
    private javax.swing.JTextField jTKey1;
    private javax.swing.JTextField jTKey2;
    private javax.swing.JTextField jTKey3;
    private javax.swing.JTextField jTPhone;
    private javax.swing.JTextField jTProductID1;
    private javax.swing.JTextField jTProductID2;
    private javax.swing.JTextField jTProductID3;
    private javax.swing.JTextField jTProductID4;
    private javax.swing.JTextField jTProductID5;
    private javax.swing.JTextField jTSerialNumber1;
    private javax.swing.JTextField jTSerialNumber2;
    private javax.swing.JTextField jTSerialNumber3;
    private javax.swing.JTextField jTStoreName;
    private javax.swing.JTextField jTZip;
    // End of variables declaration//GEN-END:variables

}
